/** UI labels for council relationship `kind` slugs (dossier machine keys stay English). */
const RELATIONSHIP_KIND_ZH: Record<string, string> = {
  adventure_buddy: "冒险拍档",
  adventure_prank: "恶作剧搭档",
  aesthetic_debate: "审美之争",
  align: "理念相合",
  ally: "同盟",
  amused: "看乐子",
  appreciate: "欣赏",
  appreciate_conservative: "欣赏·嫌保守",
  audit: "严审",
  avoid: "尽量躲开",
  baffled: "头疼",
  cautious: "谨慎",
  cautious_align: "谨慎合作",
  cautious_respect: "敬重·警惕",
  cautious_use: "利用·警惕",
  chaos_ally: "混乱同盟",
  chaos_buddy: "混乱玩伴",
  chaotic_ally: "混乱同盟",
  chess: "棋逢对手",
  chill: "同好躺平",
  clash: "理念冲突",
  close_ally: "亲密同盟",
  comfort: "照顾",
  compete: "竞争",
  conflict_caution: "冲突·警惕",
  conflict_respect: "冲突·敬重",
  cooperate: "合作",
  critique: "挑剔",
  deal: "交易",
  disdain: "不屑",
  dismissive: "轻视",
  distant: "敬而远之",
  distant_respect: "敬重·疏远",
  elder_brother: "兄长般",
  exploit: "利用",
  explore_beauty: "共赏遗迹",
  friction: "摩擦",
  frenemy: "亦敌亦友",
  gentle_conflict: "温和对立",
  gentle_cooperate: "温和合作",
  gentle_oppose: "温和反对",
  gentle_respect: "敬重·温和",
  gossip: "八卦",
  grateful: "感激",
  grateful_drag: "感激·常拖会",
  guardian: "守护",
  guide: "引导",
  helpless_care: "无奈照顾",
  impatient_respect: "敬重·嫌慢",
  interested_wary: "兴趣·警惕",
  maintain: "维护",
  mediate_pull: "调解拉扯",
  mediate_respect: "敬重·调解",
  mixed: "又爱又烦",
  nemesis: "死敌",
  opposes: "反对",
  opportunistic: "投机",
  partner: "伙伴",
  pawn: "棋子",
  peer: "同僚",
  perform: "为其表演",
  pity: "怜爱",
  pragmatic: "务实",
  prank: "恶作剧",
  puzzled: "不解",
  respect: "敬重",
  respect_caution: "敬重·谨慎",
  respect_cool: "敬重·冷淡",
  respect_differ: "敬重·分歧",
  respect_distant: "敬重·疏远",
  respect_impatient: "敬重·嫌慢",
  respect_nudge: "敬重·催细节",
  restrain: "约束",
  rival: "宿敌",
  social: "社交",
  strategic_ally: "战略同盟",
  support: "支持",
  suspicious: "猜疑",
  tease: "捉弄",
  tolerate: "勉强容忍",
  tormentor: "捉弄对象",
  tormentor_target: "重点捉弄",
  trade: "交易",
  trade_distant: "交易·疏远",
  trade_wary: "交易·警惕",
  use: "利用",
  wary: "警惕",
  wary_respect: "敬重·警惕",
  watch: "盯防",
};

export function relationshipKindLabelZh(kind: string): string {
  return RELATIONSHIP_KIND_ZH[kind] ?? kind;
}

/** All slugs with zh labels — for tests and coverage gates. */
export const COUNCIL_RELATIONSHIP_KINDS = Object.keys(RELATIONSHIP_KIND_ZH) as string[];
