/** Auto-generated by scripts/bake-beginning-fields.mjs — do not edit. */
import type { AssetSheetDef } from "./assetManifest.js";

export const ONE_CITY_TILESET_IMAGES: AssetSheetDef[] = [
  {
    "kind": "image",
    "key": "tilesets/Buildings_0_House_Hay_1.png",
    "url": "/assets/one-city/tilesets/Buildings_0_House_Hay_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Buildings_1_House_Hay_2.png",
    "url": "/assets/one-city/tilesets/Buildings_1_House_Hay_2.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Buildings_2_House_Hay_3.png",
    "url": "/assets/one-city/tilesets/Buildings_2_House_Hay_3.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Buildings_3_House_Hay_4_Purple.png",
    "url": "/assets/one-city/tilesets/Buildings_3_House_Hay_4_Purple.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Buildings_4_CityWall_Gate_1.png",
    "url": "/assets/one-city/tilesets/Buildings_4_CityWall_Gate_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Buildings_5_Well_Hay_1.png",
    "url": "/assets/one-city/tilesets/Buildings_5_Well_Hay_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_1_Bench_1.png",
    "url": "/assets/one-city/tilesets/Objects_Props_1_Bench_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_2_Bench_3.png",
    "url": "/assets/one-city/tilesets/Objects_Props_2_Bench_3.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_3_BulletinBoard_1.png",
    "url": "/assets/one-city/tilesets/Objects_Props_3_BulletinBoard_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_4_Chopped_Tree_1.png",
    "url": "/assets/one-city/tilesets/Objects_Props_4_Chopped_Tree_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_5_Crate_Large_Empty.png",
    "url": "/assets/one-city/tilesets/Objects_Props_5_Crate_Large_Empty.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_6_Crate_Medium_Closed.png",
    "url": "/assets/one-city/tilesets/Objects_Props_6_Crate_Medium_Closed.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_7_LampPost_3.png",
    "url": "/assets/one-city/tilesets/Objects_Props_7_LampPost_3.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_8_Plant_2.png",
    "url": "/assets/one-city/tilesets/Objects_Props_8_Plant_2.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_9_Sack_3.png",
    "url": "/assets/one-city/tilesets/Objects_Props_9_Sack_3.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_10_Sign_1.png",
    "url": "/assets/one-city/tilesets/Objects_Props_10_Sign_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_11_Sign_2.png",
    "url": "/assets/one-city/tilesets/Objects_Props_11_Sign_2.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_12_Banner_Stick_1_Purple.png",
    "url": "/assets/one-city/tilesets/Objects_Props_12_Banner_Stick_1_Purple.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_13_Crate_Water_1.png",
    "url": "/assets/one-city/tilesets/Objects_Props_13_Crate_Water_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_14_Fireplace_1.png",
    "url": "/assets/one-city/tilesets/Objects_Props_14_Fireplace_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_15_HayStack_2.png",
    "url": "/assets/one-city/tilesets/Objects_Props_15_HayStack_2.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_16_Barrel_Small_Empty.png",
    "url": "/assets/one-city/tilesets/Objects_Props_16_Barrel_Small_Empty.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_17_Basket_Empty.png",
    "url": "/assets/one-city/tilesets/Objects_Props_17_Basket_Empty.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Props_18_Table_Medium_1.png",
    "url": "/assets/one-city/tilesets/Objects_Props_18_Table_Medium_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Rocks_0_Rock_Brown_1.png",
    "url": "/assets/one-city/tilesets/Objects_Rocks_0_Rock_Brown_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Rocks_1_Rock_Brown_2.png",
    "url": "/assets/one-city/tilesets/Objects_Rocks_1_Rock_Brown_2.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Rocks_2_Rock_Brown_4.png",
    "url": "/assets/one-city/tilesets/Objects_Rocks_2_Rock_Brown_4.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Rocks_3_Rock_Brown_6.png",
    "url": "/assets/one-city/tilesets/Objects_Rocks_3_Rock_Brown_6.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Rocks_4_Rock_Brown_9.png",
    "url": "/assets/one-city/tilesets/Objects_Rocks_4_Rock_Brown_9.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_0_Bush_Emerald_1.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_0_Bush_Emerald_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_1_Bush_Emerald_2.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_1_Bush_Emerald_2.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_2_Bush_Emerald_3.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_2_Bush_Emerald_3.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_3_Bush_Emerald_4.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_3_Bush_Emerald_4.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_4_Bush_Emerald_5.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_4_Bush_Emerald_5.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_5_Bush_Emerald_6.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_5_Bush_Emerald_6.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_6_Bush_Emerald_7.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_6_Bush_Emerald_7.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_7_Tree_Emerald_1.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_7_Tree_Emerald_1.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_8_Tree_Emerald_2.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_8_Tree_Emerald_2.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_9_Tree_Emerald_3.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_9_Tree_Emerald_3.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Trees_10_Tree_Emerald_4.png",
    "url": "/assets/one-city/tilesets/Objects_Trees_10_Tree_Emerald_4.png"
  },
  {
    "kind": "spritesheet",
    "key": "Atlas_Props",
    "url": "/assets/one-city/tilesets/Atlas_Props.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Atlas_Rocks",
    "url": "/assets/one-city/tilesets/Atlas_Rocks.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Tileset_Ground",
    "url": "/assets/one-city/tilesets/Tileset_Ground.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Tileset_RockSlope",
    "url": "/assets/one-city/tilesets/Tileset_RockSlope.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Tileset_RockSlope_Simple",
    "url": "/assets/one-city/tilesets/Tileset_RockSlope_Simple.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Tileset_Water",
    "url": "/assets/one-city/tilesets/Tileset_Water.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Road",
    "url": "/assets/one-city/tilesets/Road.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Atlas_Trees_Bushes",
    "url": "/assets/one-city/tilesets/Atlas_Trees_Bushes.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Animation_Flowers_Red",
    "url": "/assets/one-city/tilesets/Animation_Flowers_Red.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Animation_Flowers_White",
    "url": "/assets/one-city/tilesets/Animation_Flowers_White.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Campfire",
    "url": "/assets/one-city/tilesets/Campfire.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "spritesheet",
    "key": "Tileset_Shadow",
    "url": "/assets/one-city/tilesets/Tileset_Shadow.png",
    "frameWidth": 16,
    "frameHeight": 16
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_30_Shadow_Round_16x16_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_30_Shadow_Round_16x16_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_33_Shadow_Round_16x16_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_33_Shadow_Round_16x16_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_32_Shadow_Round_16x16_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_32_Shadow_Round_16x16_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_31_Shadow_Round_16x16_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_31_Shadow_Round_16x16_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_70_Shadow_Round_16x32_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_70_Shadow_Round_16x32_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_73_Shadow_Round_16x32_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_73_Shadow_Round_16x32_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_72_Shadow_Round_16x32_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_72_Shadow_Round_16x32_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_71_Shadow_Round_16x32_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_71_Shadow_Round_16x32_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_34_Shadow_Round_24x24_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_34_Shadow_Round_24x24_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_37_Shadow_Round_24x24_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_37_Shadow_Round_24x24_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_36_Shadow_Round_24x24_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_36_Shadow_Round_24x24_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_35_Shadow_Round_24x24_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_35_Shadow_Round_24x24_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_79_Shadow_Round_24x48_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_79_Shadow_Round_24x48_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_78_Shadow_Round_24x48_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_78_Shadow_Round_24x48_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_81_Shadow_Round_24x48_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_81_Shadow_Round_24x48_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_80_Shadow_Round_24x48_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_80_Shadow_Round_24x48_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_74_Shadow_Round_32x16_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_74_Shadow_Round_32x16_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_77_Shadow_Round_32x16_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_77_Shadow_Round_32x16_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_76_Shadow_Round_32x16_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_76_Shadow_Round_32x16_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_75_Shadow_Round_32x16_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_75_Shadow_Round_32x16_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_38_Shadow_Round_32x32_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_38_Shadow_Round_32x32_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_41_Shadow_Round_32x32_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_41_Shadow_Round_32x32_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_40_Shadow_Round_32x32_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_40_Shadow_Round_32x32_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_39_Shadow_Round_32x32_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_39_Shadow_Round_32x32_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_42_Shadow_Round_40x40_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_42_Shadow_Round_40x40_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_45_Shadow_Round_40x40_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_45_Shadow_Round_40x40_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_44_Shadow_Round_40x40_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_44_Shadow_Round_40x40_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_43_Shadow_Round_40x40_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_43_Shadow_Round_40x40_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_83_Shadow_Round_48x24_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_83_Shadow_Round_48x24_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_82_Shadow_Round_48x24_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_82_Shadow_Round_48x24_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_85_Shadow_Round_48x24_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_85_Shadow_Round_48x24_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_84_Shadow_Round_48x24_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_84_Shadow_Round_48x24_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_46_Shadow_Round_48x48_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_46_Shadow_Round_48x48_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_49_Shadow_Round_48x48_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_49_Shadow_Round_48x48_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_48_Shadow_Round_48x48_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_48_Shadow_Round_48x48_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_47_Shadow_Round_48x48_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_47_Shadow_Round_48x48_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_50_Shadow_Sqare_16x16_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_50_Shadow_Sqare_16x16_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_53_Shadow_Sqare_16x16_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_53_Shadow_Sqare_16x16_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_52_Shadow_Sqare_16x16_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_52_Shadow_Sqare_16x16_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_51_Shadow_Sqare_16x16_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_51_Shadow_Sqare_16x16_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_86_Shadow_Sqare_16x32_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_86_Shadow_Sqare_16x32_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_89_Shadow_Sqare_16x32_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_89_Shadow_Sqare_16x32_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_88_Shadow_Sqare_16x32_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_88_Shadow_Sqare_16x32_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_87_Shadow_Sqare_16x32_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_87_Shadow_Sqare_16x32_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_54_Shadow_Sqare_24x24_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_54_Shadow_Sqare_24x24_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_57_Shadow_Sqare_24x24_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_57_Shadow_Sqare_24x24_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_56_Shadow_Sqare_24x24_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_56_Shadow_Sqare_24x24_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_55_Shadow_Sqare_24x24_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_55_Shadow_Sqare_24x24_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_90_Shadow_Sqare_24x48_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_90_Shadow_Sqare_24x48_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_93_Shadow_Sqare_24x48_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_93_Shadow_Sqare_24x48_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_92_Shadow_Sqare_24x48_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_92_Shadow_Sqare_24x48_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_91_Shadow_Sqare_24x48_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_91_Shadow_Sqare_24x48_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_94_Shadow_Sqare_32x16_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_94_Shadow_Sqare_32x16_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_97_Shadow_Sqare_32x16_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_97_Shadow_Sqare_32x16_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_96_Shadow_Sqare_32x16_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_96_Shadow_Sqare_32x16_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_95_Shadow_Sqare_32x16_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_95_Shadow_Sqare_32x16_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_58_Shadow_Sqare_32x32_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_58_Shadow_Sqare_32x32_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_61_Shadow_Sqare_32x32_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_61_Shadow_Sqare_32x32_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_60_Shadow_Sqare_32x32_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_60_Shadow_Sqare_32x32_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_59_Shadow_Sqare_32x32_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_59_Shadow_Sqare_32x32_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_62_Shadow_Sqare_40x40_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_62_Shadow_Sqare_40x40_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_65_Shadow_Sqare_40x40_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_65_Shadow_Sqare_40x40_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_64_Shadow_Sqare_40x40_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_64_Shadow_Sqare_40x40_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_63_Shadow_Sqare_40x40_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_63_Shadow_Sqare_40x40_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_98_Shadow_Sqare_48x24_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_98_Shadow_Sqare_48x24_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_101_Shadow_Sqare_48x24_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_101_Shadow_Sqare_48x24_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_100_Shadow_Sqare_48x24_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_100_Shadow_Sqare_48x24_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_99_Shadow_Sqare_48x24_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_99_Shadow_Sqare_48x24_Long_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_66_Shadow_Sqare_48x48_Flat_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_66_Shadow_Sqare_48x48_Flat_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_69_Shadow_Sqare_48x48_Short_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_69_Shadow_Sqare_48x48_Short_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_68_Shadow_Sqare_48x48_Medium_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_68_Shadow_Sqare_48x48_Medium_Black.png"
  },
  {
    "kind": "image",
    "key": "tilesets/Objects_Shadows_67_Shadow_Sqare_48x48_Long_Black.png",
    "url": "/assets/one-city/tilesets/Objects_Shadows_67_Shadow_Sqare_48x48_Long_Black.png"
  }
];
